<?php

return [
    'cards' => [
        'criatura:1' => ['type' => 'criatura', 'id' => 1, 'name' => 'Azzure, Sacerdotisa de Atlantis', 'rarity' => 'rara', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:2' => ['type' => 'criatura', 'id' => 2, 'name' => 'Dheron, Aprendiz de Sapomago', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:3' => ['type' => 'criatura', 'id' => 3, 'name' => 'Mysticus, Arquimago de Atlantis', 'rarity' => 'lendaria', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:4' => ['type' => 'criatura', 'id' => 4, 'name' => 'Leviathan de Esdras', 'rarity' => 'rara', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:5' => ['type' => 'criatura', 'id' => 5, 'name' => 'Atlas, Principe de Atlantis', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:6' => ['type' => 'criatura', 'id' => 6, 'name' => 'Pirata Afogado', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:7' => ['type' => 'criatura', 'id' => 7, 'name' => 'Sapomerlim, Mago dos Contos', 'rarity' => 'rara', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'criatura:8' => ['type' => 'criatura', 'id' => 8, 'name' => 'O mimico do Bau', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'habilidade:9' => ['type' => 'habilidade', 'id' => 9, 'name' => 'Tridente Poderoso de Atlas', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'habilidade:10' => ['type' => 'habilidade', 'id' => 10, 'name' => 'Tridente do Assassino', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'habilidade:11' => ['type' => 'habilidade', 'id' => 11, 'name' => 'Defesa Absoluta do Tridente', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'habilidade:12' => ['type' => 'habilidade', 'id' => 12, 'name' => 'Tridente Magico de Corais', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'habilidade:13' => ['type' => 'habilidade', 'id' => 13, 'name' => 'Reflexos de Morte', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'habilidade:14' => ['type' => 'habilidade', 'id' => 14, 'name' => 'Afogamento', 'rarity' => 'comum', 'element' => 'agua', 'edition' => 'Abismos & Profundezas'],
        'item:15' => ['type' => 'item', 'id' => 15, 'name' => 'Verdadeiro Tridente de Atlantis', 'rarity' => 'rara', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'item:17' => ['type' => 'item', 'id' => 17, 'name' => 'Esfera da Aura Espectral', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'item:20' => ['type' => 'item', 'id' => 20, 'name' => 'Pote da Sereia', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:21' => ['type' => 'comando', 'id' => 21, 'name' => 'Riso Histerico de Tashaa O', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:22' => ['type' => 'comando', 'id' => 22, 'name' => 'Escolha as Cegas', 'rarity' => 'lendaria', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:23' => ['type' => 'comando', 'id' => 23, 'name' => 'Marionete de Guerra', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:24' => ['type' => 'comando', 'id' => 24, 'name' => 'Olho do Antigo Oraculo', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:25' => ['type' => 'comando', 'id' => 25, 'name' => 'Ritual da Esfera Espectral', 'rarity' => 'rara', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:26' => ['type' => 'comando', 'id' => 26, 'name' => 'Lua Sangrenta de Esdras', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'comando:27' => ['type' => 'comando', 'id' => 27, 'name' => 'Alterando as Rotas', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Abismos & Profundezas'],
        'criatura:28' => ['type' => 'criatura', 'id' => 28, 'name' => 'Lobo do Uivo sombrio', 'rarity' => 'rara', 'element' => 'terra', 'edition' => 'Matilhas & Predadores'],
        'criatura:29' => ['type' => 'criatura', 'id' => 29, 'name' => 'Lobo das Presas Prateadas', 'rarity' => 'comum', 'element' => 'terra', 'edition' => 'Matilhas & Predadores'],
        'criatura:30' => ['type' => 'criatura', 'id' => 30, 'name' => 'Badur, o Bebe Urso', 'rarity' => 'comum', 'element' => 'terra', 'edition' => 'Matilhas & Predadores'],
        'criatura:31' => ['type' => 'criatura', 'id' => 31, 'name' => 'Badur, o Urso Guardiao', 'rarity' => 'lendaria', 'element' => 'terra', 'edition' => 'Matilhas & Predadores'],
        'criatura:32' => ['type' => 'criatura', 'id' => 32, 'name' => 'Feiticeiro Tribal Badur', 'rarity' => 'comum', 'element' => 'terra', 'edition' => 'Matilhas & Predadores'],
        'criatura:33' => ['type' => 'criatura', 'id' => 33, 'name' => 'Sapotristan, o Escudeiro dos Contos', 'rarity' => 'rara', 'element' => 'terra', 'edition' => 'Matilhas & Predadores'],
        'criatura:34' => ['type' => 'criatura', 'id' => 34, 'name' => 'Poltergeist, Voz do Vacuo', 'rarity' => 'comum', 'element' => 'vazio', 'edition' => 'Matilhas & Predadores'],
        'criatura:35' => ['type' => 'criatura', 'id' => 35, 'name' => 'Ceifador do castelo Amaldicoado', 'rarity' => 'rara', 'element' => 'vazio', 'edition' => 'Matilhas & Predadores'],
        'criatura:36' => ['type' => 'criatura', 'id' => 36, 'name' => 'Mamuthe Ancestral', 'rarity' => 'comum', 'element' => 'vazio', 'edition' => 'Matilhas & Predadores'],
        'item:16' => ['type' => 'item', 'id' => 16, 'name' => 'Sapocalibur, A Espada Lendaria', 'rarity' => 'lendaria', 'element' => 'neutro', 'edition' => 'Matilhas & Predadores'],
        'item:18' => ['type' => 'item', 'id' => 18, 'name' => 'Mapa do Tesouro', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Matilhas & Predadores'],
        'item:19' => ['type' => 'item', 'id' => 19, 'name' => 'Manopla do Poder', 'rarity' => 'comum', 'element' => 'neutro', 'edition' => 'Matilhas & Predadores'],
        'cenario:45' => ['type' => 'cenario', 'id' => 45, 'name' => 'Caverna do Guardiao Badur', 'rarity' => 'rara', 'element' => 'neutro', 'edition' => 'Matilhas & Predadores'],
    ],
    'essence_by_rarity' => [
        'comum' => 12,
        'rara' => 25,
        'lendaria' => 50,
    ],
    'booster_editions' => [
        ['key' => 'abismos_profundezas', 'name' => 'Abismos & Profundezas', 'price_crystals' => 250, 'available' => true],
        ['key' => 'matilhas_predadores', 'name' => 'Matilhas & Predadores', 'price_crystals' => 250, 'available' => true],
        ['key' => 'ecos_do_vazio', 'name' => 'Ecos do Vazio', 'price_crystals' => 250, 'available' => false],
        ['key' => 'forjas_elementais', 'name' => 'Forjas Elementais', 'price_crystals' => 250, 'available' => false],
        ['key' => 'torres_arcanas', 'name' => 'Torres Arcanas', 'price_crystals' => 250, 'available' => false],
    ],
];
