<?php

return [
    'abismos_profundezas' => [
        'name' => 'Abismos & Profundezas',
        'element' => 'agua',
        'description' => 'Um baralho de Água focado em Atlantis, tridentes e controle de combate.',
        'npc_image' => 'tutor_elements',
        'cover' => ['uid' => 'criatura:3', 'type' => 'criatura', 'id' => 3],
        'cards' => [
            ['uid' => 'criatura:1', 'type' => 'criatura', 'id' => 1, 'qty' => 2],
            ['uid' => 'criatura:2', 'type' => 'criatura', 'id' => 2, 'qty' => 2],
            ['uid' => 'criatura:3', 'type' => 'criatura', 'id' => 3, 'qty' => 1],
            ['uid' => 'criatura:4', 'type' => 'criatura', 'id' => 4, 'qty' => 1],
            ['uid' => 'criatura:5', 'type' => 'criatura', 'id' => 5, 'qty' => 2],
            ['uid' => 'criatura:6', 'type' => 'criatura', 'id' => 6, 'qty' => 3],
            ['uid' => 'criatura:7', 'type' => 'criatura', 'id' => 7, 'qty' => 2],
            ['uid' => 'criatura:8', 'type' => 'criatura', 'id' => 8, 'qty' => 2],
            ['uid' => 'habilidade:9', 'type' => 'habilidade', 'id' => 9, 'qty' => 2],
            ['uid' => 'habilidade:10', 'type' => 'habilidade', 'id' => 10, 'qty' => 2],
            ['uid' => 'habilidade:11', 'type' => 'habilidade', 'id' => 11, 'qty' => 1],
            ['uid' => 'habilidade:12', 'type' => 'habilidade', 'id' => 12, 'qty' => 1],
            ['uid' => 'habilidade:13', 'type' => 'habilidade', 'id' => 13, 'qty' => 1],
            ['uid' => 'habilidade:14', 'type' => 'habilidade', 'id' => 14, 'qty' => 1],
            ['uid' => 'item:15', 'type' => 'item', 'id' => 15, 'qty' => 1],
            ['uid' => 'item:20', 'type' => 'item', 'id' => 20, 'qty' => 2],
            ['uid' => 'comando:21', 'type' => 'comando', 'id' => 21, 'qty' => 2],
            ['uid' => 'comando:22', 'type' => 'comando', 'id' => 22, 'qty' => 1],
            ['uid' => 'comando:24', 'type' => 'comando', 'id' => 24, 'qty' => 1],
        ],
    ],

    'matilha_predadores' => [
        'name' => 'Matilha & Predadores',
        'element' => 'terra',
        'description' => 'Um baralho de Terra com Bestas, Badur e pressão de campo.',
        'npc_image' => 'tutor_elements',
        'cover' => ['uid' => 'criatura:30', 'type' => 'criatura', 'id' => 30],
        'cards' => [
            ['uid' => 'criatura:28', 'type' => 'criatura', 'id' => 28, 'qty' => 2],
            ['uid' => 'criatura:29', 'type' => 'criatura', 'id' => 29, 'qty' => 2],
            ['uid' => 'criatura:30', 'type' => 'criatura', 'id' => 30, 'qty' => 3],
            ['uid' => 'criatura:31', 'type' => 'criatura', 'id' => 31, 'qty' => 2],
            ['uid' => 'criatura:32', 'type' => 'criatura', 'id' => 32, 'qty' => 2],
            ['uid' => 'criatura:33', 'type' => 'criatura', 'id' => 33, 'qty' => 2],
            ['uid' => 'criatura:34', 'type' => 'criatura', 'id' => 34, 'qty' => 2],
            ['uid' => 'criatura:35', 'type' => 'criatura', 'id' => 35, 'qty' => 1],
            ['uid' => 'criatura:36', 'type' => 'criatura', 'id' => 36, 'qty' => 2],
            ['uid' => 'item:16', 'type' => 'item', 'id' => 16, 'qty' => 1],
            ['uid' => 'item:18', 'type' => 'item', 'id' => 18, 'qty' => 1],
            ['uid' => 'item:19', 'type' => 'item', 'id' => 19, 'qty' => 3],
            ['uid' => 'comando:23', 'type' => 'comando', 'id' => 23, 'qty' => 3],
            ['uid' => 'comando:25', 'type' => 'comando', 'id' => 25, 'qty' => 1],
            ['uid' => 'comando:26', 'type' => 'comando', 'id' => 26, 'qty' => 1],
            ['uid' => 'comando:27', 'type' => 'comando', 'id' => 27, 'qty' => 3],
            ['uid' => 'cenario:45', 'type' => 'cenario', 'id' => 45, 'qty' => 1],
        ],
    ],

    'goblins_promessas' => [
        'name' => 'Goblins & Promessas',
        'element' => 'fogo',
        'description' => 'Starter de Fogo reservado para a coleção Goblins. Usa cartas neutras temporárias até a coleção entrar.',
        'npc_image' => 'tutor_spell',
        'cover' => ['uid' => 'criatura:34', 'type' => 'criatura', 'id' => 34],
        'cards' => [
            ['uid' => 'criatura:6', 'type' => 'criatura', 'id' => 6, 'qty' => 2],
            ['uid' => 'criatura:8', 'type' => 'criatura', 'id' => 8, 'qty' => 2],
            ['uid' => 'criatura:28', 'type' => 'criatura', 'id' => 28, 'qty' => 2],
            ['uid' => 'criatura:29', 'type' => 'criatura', 'id' => 29, 'qty' => 2],
            ['uid' => 'criatura:30', 'type' => 'criatura', 'id' => 30, 'qty' => 2],
            ['uid' => 'criatura:34', 'type' => 'criatura', 'id' => 34, 'qty' => 4],
            ['uid' => 'habilidade:10', 'type' => 'habilidade', 'id' => 10, 'qty' => 2],
            ['uid' => 'habilidade:13', 'type' => 'habilidade', 'id' => 13, 'qty' => 1],
            ['uid' => 'item:17', 'type' => 'item', 'id' => 17, 'qty' => 2],
            ['uid' => 'item:18', 'type' => 'item', 'id' => 18, 'qty' => 2],
            ['uid' => 'item:19', 'type' => 'item', 'id' => 19, 'qty' => 1],
            ['uid' => 'comando:21', 'type' => 'comando', 'id' => 21, 'qty' => 2],
            ['uid' => 'comando:22', 'type' => 'comando', 'id' => 22, 'qty' => 2],
            ['uid' => 'comando:23', 'type' => 'comando', 'id' => 23, 'qty' => 1],
            ['uid' => 'comando:26', 'type' => 'comando', 'id' => 26, 'qty' => 1],
            ['uid' => 'comando:27', 'type' => 'comando', 'id' => 27, 'qty' => 2],
        ],
    ],

    'guardioes_penas' => [
        'name' => 'Guardiões & Penas',
        'element' => 'vento',
        'description' => 'Starter de Vento reservado para Guardiões. Usa cartas de suporte temporárias até a coleção entrar.',
        'npc_image' => 'tutor_explain',
        'cover' => ['uid' => 'criatura:32', 'type' => 'criatura', 'id' => 32],
        'cards' => [
            ['uid' => 'criatura:1', 'type' => 'criatura', 'id' => 1, 'qty' => 1],
            ['uid' => 'criatura:2', 'type' => 'criatura', 'id' => 2, 'qty' => 2],
            ['uid' => 'criatura:7', 'type' => 'criatura', 'id' => 7, 'qty' => 2],
            ['uid' => 'criatura:30', 'type' => 'criatura', 'id' => 30, 'qty' => 2],
            ['uid' => 'criatura:31', 'type' => 'criatura', 'id' => 31, 'qty' => 2],
            ['uid' => 'criatura:32', 'type' => 'criatura', 'id' => 32, 'qty' => 3],
            ['uid' => 'criatura:33', 'type' => 'criatura', 'id' => 33, 'qty' => 2],
            ['uid' => 'criatura:36', 'type' => 'criatura', 'id' => 36, 'qty' => 2],
            ['uid' => 'habilidade:11', 'type' => 'habilidade', 'id' => 11, 'qty' => 2],
            ['uid' => 'habilidade:12', 'type' => 'habilidade', 'id' => 12, 'qty' => 2],
            ['uid' => 'habilidade:14', 'type' => 'habilidade', 'id' => 14, 'qty' => 1],
            ['uid' => 'item:16', 'type' => 'item', 'id' => 16, 'qty' => 1],
            ['uid' => 'item:20', 'type' => 'item', 'id' => 20, 'qty' => 2],
            ['uid' => 'comando:24', 'type' => 'comando', 'id' => 24, 'qty' => 2],
            ['uid' => 'comando:25', 'type' => 'comando', 'id' => 25, 'qty' => 1],
            ['uid' => 'comando:27', 'type' => 'comando', 'id' => 27, 'qty' => 2],
            ['uid' => 'cenario:45', 'type' => 'cenario', 'id' => 45, 'qty' => 1],
        ],
    ],
];
